<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Based on the TextMate XML syntax with help from the Ant bundle and the JSP language.
    
    Some notes:
    * We ignore namespaces. Phing will croak with them.
    * Currently, we support build.xml and phing.xml file types.
    
    TODO:
    </string>
	<key>fileTypes</key>
	<array>
		<string>build.xml</string>
		<string>phing.xml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
            (&lt;(?i:foo|project|fileset|target|echo)\b.*?&gt;
            |&lt;!--(?!.*--&gt;)
            |\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
            )</string>
	<key>foldingStopMarker</key>
	<string>(?x)
            (&lt;/(?i:foo|project|fileset|target|echo)&gt;
            |^\s*--&gt;
            |(^|\s)\}
            )</string>
	<key>name</key>
	<string>Phing</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)(xml)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.phing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>name</key>
			<string>meta.tag.preprocessor.xml.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> ([a-zA-Z-]+)</string>
					<key>name</key>
					<string>entity.other.attribute-name.phing</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--%?&gt;</string>
			<key>name</key>
			<string>comment.block.phing</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)(target)\s(name)="([\w\-_]+)"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.localname.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.phing</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.target.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;echo&gt;</string>
			<key>contentName</key>
			<string>string.unquoted.echo.phing</string>
			<key>end</key>
			<string>&lt;/echo&gt;</string>
			<key>name</key>
			<string>meta.tag.echo.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated-variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)([-_a-zA-Z0-9:]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.phing</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tagStuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#entity</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bare-ampersand</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;!\[CDATA\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.phing</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>I do not know if Phing respects CDATA sections.</string>
			<key>end</key>
			<string>]]&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.phing</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.cdata.phing</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bare-ampersand</key>
		<dict>
			<key>match</key>
			<string>&amp;</string>
			<key>name</key>
			<string>invalid.illegal.bad-ampersand.phing</string>
		</dict>
		<key>doublequotedString</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.phing</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bare-ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-variable</string>
				</dict>
			</array>
		</dict>
		<key>entity</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.phing</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.phing</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&amp;)([:a-zA-Z_][:a-zA-Z0-9_.-]*|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
			<key>name</key>
			<string>constant.character.entity.xml</string>
		</dict>
		<key>interpolated-variable</key>
		<dict>
			<key>begin</key>
			<string>\${</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.phing</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>This seems to be how vars interpolated into text are usually labeled.</string>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.phing</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>singlequotedString</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.phing</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.phing</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.phing</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bare-ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated-variable</string>
				</dict>
			</array>
		</dict>
		<key>tagStuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.phing</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s([-_a-zA-Z0-9]+)=</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotedString</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotedString</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.phing</string>
	<key>uuid</key>
	<string>DF03CBDC-6CA2-4F41-8FF5-5CD0B60DE308</string>
</dict>
</plist>
